repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.3
    hooks:
      - id: ruff
      - id: ruff-format
        args:
          - --exclude
          - domains/**.py

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: requirements-txt-fixer
      - id: end-of-file-fixer
        exclude: domains.*\.py
      - id: trailing-whitespace
        exclude: domains.*\.py
