name: Code checks and tests

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4
      - name: Add uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true
          cache-suffix: "optional-suffix"
      - name: Install dependencies
        run: uv sync
      - name: Run ruff check
        run: uv run ruff check --output-format=github .
      - name: Run tests
        run: uv run pytest -v
