name: Publish to PyPI

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for trusted publishing

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          
      - name: Extract version from tag
        run: |
          echo "VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
          echo "VERSION=${GITHUB_REF#refs/*/v}"
          echo "ref:  ${GITHUB_REF#refs/*/v}"  # refs/tags/v0.3.1

        
      - name: Update pyproject.toml with new version
        run: |
          sed -i 's|^version = "[^"]*"|version = "'"$VERSION"'"|' pyproject.toml
          
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install build dependencies
        run: uv pip install --system build

      - name: Build package
        run: python -m build
        
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1